spring:
  couchbase:
    connection-string: "127.0.0.1"
    user-name: "rahul"
    password: "admin@123"
    bucket-name: "product"
logging:
  file: 
    name: #(paste the path where your .log is present for example : /Users/harshith.sr/Downloads/logs/elk-stack.log)