spring:
  couchbase:
    connection-string: "127.0.0.1"
    user-name: "mdep"
    password: "rakuten"
    bucket-name: "product"
logging:
  file: 
    name: /Users/harshith.sr/Downloads/logs/elk-stack.log 
